[package]
name = "solito"
version = "0.2.0"
edition = "2024"
license.workspace = true

[dependencies]
arboard = { version = "3", default-features = false }
portable-pty = "0.9.0"
winit.workspace = true
tracing.workspace = true
anyhow.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
pollster = "1.0.1"
solito-renderer = { path = "../solito-renderer" }
solito-terminal = { path = "../solito-terminal" }
solito-config = { path = "../solito-config" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
winresource = "0.1"
